#!/usr/bin/env python3
"""
Global all-slice motion-pattern x CFU lag co-occurrence.

Statistical procedure
---------------------
For every motion-pattern / CFU pair:

1. Evaluate lagged co-occurrence for lag = -8 ... +8.
2. For each lag, calculate a binomial enrichment p-value.
3. Convert the lag-wise p-value to an enrichment score:
       score = -log10(p)
4. Define the pair statistic as the maximum score across all lags:
       S_pair = max_lag score(lag)

The 17-lag search is therefore part of the pair statistic and is NOT
Bonferroni-corrected separately.

Global multiple-testing correction
----------------------------------
A shift-null is constructed by applying the SAME circular temporal shift
to all CFU onset trains simultaneously. This preserves:

- the number of onsets in every CFU,
- temporal structure within every CFU,
- relative timing among different CFUs,
- all motion-pattern timing,

while destroying the absolute Ca-vs-motion temporal alignment.

For every null shift, the COMPLETE analysis is repeated, including the
search over all 17 lags for all pattern-CFU pairs.

For score threshold s:

    R_obs(s) = number of observed pairs with score >= s

    V_null(s) = expected number of null pairs with score >= s

and

    empirical_FDR(s) = V_null(s) / R_obs(s)

Pair-level empirical q-values are obtained from the monotone FDR envelope.

IMPORTANT
---------
CFU timing uses cfuInfo1{i,4}, i.e. the AQuA2 CFU rising-time/onset
binary timeline generated by getRisingTime(), NOT res.fts1.loc.t0.
"""

from __future__ import annotations

import csv
import pickle
import sys
from pathlib import Path

import h5py
import numpy as np
from scipy.signal import find_peaks
from scipy.stats import binom


# ============================================================
# Configuration
# ============================================================

BASE = Path("/home/cyf/wbi/wbi_code")

sys.path.insert(0, str(BASE))
sys.path.insert(1, str(BASE / "code"))

OUT = (
    BASE
    / "experiments/Fig5_v0827/04_all_pattern_cfu_lag_cooccurrence"
    / "results/global_shift_empirical_fdr_onset"
)

RESULTS = OUT

CFU_BASE = (
    BASE
    / "experiments/Fig5_v0827/02_current_cfu_input/cfu"
)

PAT_BASE = BASE / "experiments/Fig5_v0827/01_motion_pattern_extraction_omega05_mu05/patterns"


# Movie length
T = 1598

# Seconds per frame
FRAME_SECONDS = 3.80843294434


# ----------------------------
# Motion-pattern filtering
# ----------------------------

MIN_PATTERN_MEMBERS = 5
MIN_MOTION_EVENTS = 5

MOTION_PROMINENCE_FACTOR = 0.50
MOTION_MIN_DISTANCE = 10


# ----------------------------
# Co-occurrence definition
# ----------------------------

WINDOW_W = 3

LAG_MIN = -8
LAG_MAX = 8

LAGS = np.arange(LAG_MIN, LAG_MAX + 1, dtype=int)


# ----------------------------
# Empirical global FDR
# ----------------------------

FDR_ALPHA = 0.05

# Number of circular-shift null realizations.
#
# Set to None to use ALL admissible circular shifts.
# For initial runs, 300-500 is usually a reasonable compromise.
N_NULL_SHIFTS = 500

RANDOM_SEED = 20260826

# A null shift too close to zero can be compensated by the lag search.
#
# lag range = +/- 8
# window width = 3
#
# Therefore exclude shifts whose circular distance from zero is <= 10.
NULL_GUARD_FRAMES = max(abs(LAG_MIN), abs(LAG_MAX)) + WINDOW_W - 1


# Numerical floor for -log10(p)
P_FLOOR = 1e-300


# Saving all 6.5 million lag-wise rows creates a large CSV.
# Set False if only pair-level results are needed.
SAVE_ALL_LAG_ROWS = True


# ============================================================
# Utility
# ============================================================

def save_csv(path: Path, rows, fieldnames=None):
    """Save a list/iterator of dictionaries."""
    path.parent.mkdir(parents=True, exist_ok=True)

    rows = list(rows)

    if fieldnames is None:
        if rows:
            fieldnames = list(rows[0].keys())
        else:
            fieldnames = ["empty"]

    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        if rows:
            writer.writerows(rows)


# ============================================================
# Read AQuA2 CFU onset timelines
# ============================================================

def _detect_cfu_cell_layout(cells):
    """
    MATLAB cell arrays are dimension-reversed when viewed through h5py.

    Typical MATLAB:
        nCFU x 9

    appears as:
        9 x nCFU

    in HDF5/h5py.
    """

    if cells.ndim != 2:
        raise RuntimeError(
            f"Unexpected cfuInfo1 shape: {cells.shape}"
        )

    # Standard AQuA2 cfuInfo1 has 9 fields.
    # Some newer versions may have 10.
    if cells.shape[0] in (9, 10):
        return "field_first", cells.shape[1]

    if cells.shape[1] in (9, 10):
        return "cfu_first", cells.shape[0]

    raise RuntimeError(
        "Cannot determine cfuInfo1 orientation. "
        f"Shape = {cells.shape}"
    )


def _get_cfu_field_ref(cells, layout, cid0, field0):
    """Get the HDF5 reference for one CFU field."""

    if layout == "field_first":
        return cells[field0, cid0]

    return cells[cid0, field0]


def cfu_event_onsets(z):
    """
    Read AQuA2 CFU onset timelines.

    Uses:
        cfuInfo1{i,4}

    which corresponds to the binary CFU occurrence/onset timeline
    calculated by cfu.getRisingTime().

    Returns
    -------
    list of tuples:
        (
            cfu_id_1based,
            n_member_events,
            onset_frames_0based
        )
    """

    cfu_file = (
        CFU_BASE
        / f"slice_Z{z:02d}_ds7_native_CFU_ot030_min5_group5.mat"
    )

    out = []

    with h5py.File(cfu_file, "r") as cf:

        cells = cf["cfuInfo1"]

        layout, n_cfus = _detect_cfu_cell_layout(cells)

        for cid0 in range(n_cfus):

            # ------------------------------------------------
            # Column 2 in MATLAB:
            # cfuInfo1{i,2} = member event IDs
            # ------------------------------------------------

            member_ref = _get_cfu_field_ref(
                cells,
                layout,
                cid0,
                field0=1,
            )

            member_ids = np.asarray(
                cf[member_ref]
            ).reshape(-1)

            n_member_events = len(member_ids)


            # ------------------------------------------------
            # Column 4 in MATLAB:
            # cfuInfo1{i,4} = onset/occurrence binary timeline
            # ------------------------------------------------

            onset_ref = _get_cfu_field_ref(
                cells,
                layout,
                cid0,
                field0=3,
            )

            onset_timeline = np.asarray(
                cf[onset_ref]
            ).reshape(-1)

            if onset_timeline.size != T:
                raise RuntimeError(
                    f"CFU onset timeline length mismatch: "
                    f"slice={z}, cfu={cid0 + 1}, "
                    f"found={onset_timeline.size}, expected={T}"
                )

            onsets = np.flatnonzero(onset_timeline > 0)

            onsets = np.asarray(
                onsets,
                dtype=np.int32,
            )

            out.append(
                (
                    cid0 + 1,
                    n_member_events,
                    onsets,
                )
            )

    return out


# ============================================================
# Motion-pattern activity peaks
# ============================================================

def component_frames(c):
    """Extract frame indices and activity values from one component."""

    h = np.asarray(
        getattr(c, "activation", None),
        dtype=float,
    ).reshape(-1)

    tr = getattr(c, "time_range", None)

    if tr is None or not len(h):
        return (
            np.empty(0, dtype=int),
            np.empty(0, dtype=float),
        )

    a, b = int(tr[0]), int(tr[1])

    if b - a == len(h):
        frames = np.arange(a, b)

    elif b - a + 1 == len(h):
        frames = np.arange(a, b + 1)

    else:
        frames = np.arange(a, a + len(h))

    ok = (frames >= 0) & (frames < T)

    return frames[ok], h[ok]


def motion_event_peaks(z):
    """
    Extract motion occurrence peaks for all retained patterns
    from one slice.
    """

    path = (
        PAT_BASE
        / f"Slice{z:02d}_velocity_decomp"
        / "06_patterns"
        / "objects.pkl"
    )

    with path.open("rb") as f:
        patterns = pickle.load(f)["patterns"]

    out = []

    for p in patterns:

        n_members = int(p.n_members)

        if n_members < MIN_PATTERN_MEMBERS:
            continue

        comps = (
            getattr(p, "components", None)
            or getattr(p, "regions", [])
        )

        sq = np.zeros(T, dtype=float)
        count = np.zeros(T, dtype=np.int16)

        for c in comps:

            frames, h = component_frames(c)

            if len(frames):
                sq[frames] += h * h
                count[frames] += 1

        x = np.zeros(T, dtype=float)

        ok = count > 0

        x[ok] = np.sqrt(
            sq[ok] / count[ok]
        )

        x = np.nan_to_num(
            x,
            nan=np.nanmedian(x),
        )

        prom = max(
            MOTION_PROMINENCE_FACTOR * np.std(x),
            1e-8,
        )

        peaks, _ = find_peaks(
            x,
            prominence=prom,
            distance=MOTION_MIN_DISTANCE,
        )

        if len(peaks) >= MIN_MOTION_EVENTS:

            out.append(
                (
                    int(p.pattern_id),
                    n_members,
                    np.asarray(peaks, dtype=np.int32),
                )
            )

    return out


# ============================================================
# Build CFU onset matrix
# ============================================================

def build_onset_matrix(cfus):
    """
    Binary matrix:

        shape = (n_CFU, T)

    onset_matrix[c,t] = True
    if CFU c has an onset at frame t.
    """

    mat = np.zeros(
        (len(cfus), T),
        dtype=bool,
    )

    for ci, (_, _, _, onsets) in enumerate(cfus):

        if len(onsets):
            mat[ci, onsets] = True

    return mat


# ============================================================
# Window-hit matrix
# ============================================================

def build_window_hit_matrix(onset_matrix):
    """
    For every CFU and every possible window start s:

        hit[c,s] = 1

    if there is >=1 onset in:

        [s, s + WINDOW_W)

    Shape:
        (n_CFU, T - WINDOW_W + 1)
    """

    x = onset_matrix.astype(
        np.int32,
        copy=False,
    )

    prefix = np.concatenate(
        [
            np.zeros(
                (x.shape[0], 1),
                dtype=np.int32,
            ),
            np.cumsum(
                x,
                axis=1,
                dtype=np.int32,
            ),
        ],
        axis=1,
    )

    counts = (
        prefix[:, WINDOW_W:]
        -
        prefix[:, :-WINDOW_W]
    )

    return counts > 0


# ============================================================
# Precompute motion windows for every pattern / lag
# ============================================================

def precompute_pattern_lag_starts(patterns):
    """
    For every pattern and every lag, store valid window starts.

    Edge-invalid motion events are removed independently at each lag.
    """

    all_starts = []

    unique_n_trials = set()

    for _, _, _, peaks in patterns:

        per_pattern = []

        for lag in LAGS:

            starts = peaks + lag

            valid = (
                (starts >= 0)
                &
                (starts + WINDOW_W <= T)
            )

            starts = np.asarray(
                starts[valid],
                dtype=np.int32,
            )

            per_pattern.append(starts)

            if len(starts):
                unique_n_trials.add(
                    int(len(starts))
                )

        all_starts.append(per_pattern)

    return all_starts, sorted(unique_n_trials)


# ============================================================
# Precompute binomial score lookup tables
# ============================================================

def build_binomial_lookup(unique_n_trials, p_window):
    """
    Since n_trials and CFU baseline rate do not change across null shifts,
    precompute:

        p(K >= k | n, p_window)

    for every needed:
        n_trials
        CFU
        k
    """

    n_cfus = len(p_window)

    cfu_idx = np.arange(n_cfus)

    p_tables = {}
    score_tables = {}

    for n in unique_n_trials:

        k_values = np.arange(
            n + 1,
            dtype=int,
        )

        # Shape:
        #   (n_CFU, n+1)
        p_table = binom.sf(
            k_values[None, :] - 1,
            n,
            p_window[:, None],
        )

        p_table = np.clip(
            p_table,
            P_FLOOR,
            1.0,
        )

        score_table = -np.log10(
            p_table
        )

        p_tables[n] = p_table
        score_tables[n] = score_table

    return p_tables, score_tables


# ============================================================
# Calculate pair-wise best-lag statistic
# ============================================================

def compute_best_pair_scores(
    window_hits,
    pattern_lag_starts,
    p_tables,
    score_tables,
    return_details=False,
):
    """
    Calculate:

        S_pair = max_lag -log10(p_binomial)

    for every motion-pattern x CFU pair.
    """

    n_patterns = len(pattern_lag_starts)
    n_cfus = window_hits.shape[0]

    cfu_idx = np.arange(n_cfus)

    best_score = np.full(
        (n_patterns, n_cfus),
        -np.inf,
        dtype=np.float64,
    )

    if return_details:

        best_p = np.ones(
            (n_patterns, n_cfus),
            dtype=np.float64,
        )

        best_lag = np.full(
            (n_patterns, n_cfus),
            32767,
            dtype=np.int16,
        )

        best_k = np.zeros(
            (n_patterns, n_cfus),
            dtype=np.int16,
        )

        best_n_trials = np.zeros(
            (n_patterns, n_cfus),
            dtype=np.int16,
        )

    for pi, per_pattern in enumerate(pattern_lag_starts):

        for li, lag in enumerate(LAGS):

            starts = per_pattern[li]

            n_trials = len(starts)

            if n_trials == 0:
                continue

            # Number of motion occurrences that hit >=1 CFU onset
            #
            # window_hits[:, starts]:
            #     shape = (n_CFU, n_motion_events)
            #
            k = np.sum(
                window_hits[:, starts],
                axis=1,
            ).astype(np.int16)

            scores = score_tables[n_trials][
                cfu_idx,
                k,
            ]

            if not return_details:

                best_score[pi] = np.maximum(
                    best_score[pi],
                    scores,
                )

                continue


            pvals = p_tables[n_trials][
                cfu_idx,
                k,
            ]


            # Primary criterion:
            # larger score = stronger association
            better = (
                scores
                >
                best_score[pi] + 1e-12
            )


            # Tie breaking:
            #
            # If exactly equal evidence appears at several lags,
            # prefer the lag closer to zero.
            equal = np.isclose(
                scores,
                best_score[pi],
                rtol=0,
                atol=1e-12,
            )

            closer_to_zero = (
                np.abs(lag)
                <
                np.abs(best_lag[pi])
            )

            update = (
                better
                |
                (equal & closer_to_zero)
            )


            best_score[pi, update] = scores[update]

            best_p[pi, update] = pvals[update]

            best_lag[pi, update] = lag

            best_k[pi, update] = k[update]

            best_n_trials[pi, update] = n_trials


    if not return_details:

        return best_score


    return (
        best_score,
        best_p,
        best_lag,
        best_k,
        best_n_trials,
    )


# ============================================================
# Null circular shifts
# ============================================================

def choose_null_shifts():
    """
    Select global circular shifts.

    Small shifts are excluded because they can be compensated by the
    +/-8-frame lag search.
    """

    valid = []

    for shift in range(1, T):

        circular_distance = min(
            shift,
            T - shift,
        )

        if circular_distance <= NULL_GUARD_FRAMES:
            continue

        valid.append(shift)

    valid = np.asarray(
        valid,
        dtype=np.int32,
    )

    if (
        N_NULL_SHIFTS is None
        or N_NULL_SHIFTS >= len(valid)
    ):

        return valid

    rng = np.random.default_rng(
        RANDOM_SEED
    )

    shifts = rng.choice(
        valid,
        size=N_NULL_SHIFTS,
        replace=False,
    )

    return np.sort(shifts)


# ============================================================
# Empirical global FDR
# ============================================================

def empirical_global_fdr(
    observed_scores,
    onset_matrix,
    pattern_lag_starts,
    p_tables,
    score_tables,
):
    """
    Estimate global empirical FDR using whole-Ca-system circular shifts.
    """

    observed_flat = observed_scores.reshape(-1)

    n_pairs = len(observed_flat)


    # --------------------------------------------------------
    # Unique observed score thresholds
    # --------------------------------------------------------

    thresholds_asc, inverse = np.unique(
        observed_flat,
        return_inverse=True,
    )

    thresholds_desc = thresholds_asc[::-1]


    # --------------------------------------------------------
    # Number of observed discoveries at each threshold
    # --------------------------------------------------------

    observed_sorted = np.sort(
        observed_flat
    )

    n_observed = (
        n_pairs
        -
        np.searchsorted(
            observed_sorted,
            thresholds_desc,
            side="left",
        )
    ).astype(np.float64)


    # --------------------------------------------------------
    # Null shifts
    # --------------------------------------------------------

    shifts = choose_null_shifts()

    null_exceed_sum = np.zeros(
        len(thresholds_desc),
        dtype=np.float64,
    )

    print(
        f"Running {len(shifts)} global circular-shift nulls...",
        flush=True,
    )

    for bi, shift in enumerate(shifts, start=1):

        # Same temporal shift for EVERY CFU.
        shifted_onsets = np.roll(
            onset_matrix,
            shift=int(shift),
            axis=1,
        )

        shifted_hits = build_window_hit_matrix(
            shifted_onsets
        )

        null_scores = compute_best_pair_scores(
            shifted_hits,
            pattern_lag_starts,
            p_tables,
            score_tables,
            return_details=False,
        )

        null_flat = np.sort(
            null_scores.reshape(-1)
        )

        n_null = (
            n_pairs
            -
            np.searchsorted(
                null_flat,
                thresholds_desc,
                side="left",
            )
        )

        null_exceed_sum += n_null


        if (
            bi == 1
            or bi % 10 == 0
            or bi == len(shifts)
        ):

            print(
                f"  null shift {bi}/{len(shifts)} "
                f"(shift={int(shift)} frames)",
                flush=True,
            )


    # --------------------------------------------------------
    # Expected number of false discoveries
    # --------------------------------------------------------
    #
    # Add-one smoothing avoids an exact zero estimate.
    #

    mean_null_discoveries = (
        1.0 + null_exceed_sum
    ) / (
        len(shifts) + 1.0
    )


    # --------------------------------------------------------
    # Raw empirical FDR
    # --------------------------------------------------------

    fdr_raw_desc = (
        mean_null_discoveries
        /
        np.maximum(
            n_observed,
            1.0,
        )
    )

    fdr_raw_desc = np.minimum(
        fdr_raw_desc,
        1.0,
    )


    # --------------------------------------------------------
    # Convert threshold FDR to monotone q-values
    # --------------------------------------------------------
    #
    # thresholds_desc:
    #
    # high score -> low score
    #
    # q(s) =
    #   minimum FDR among all thresholds that still include score s
    #

    q_desc = np.minimum.accumulate(
        fdr_raw_desc[::-1]
    )[::-1]


    # Convert back to ascending threshold ordering
    q_asc = q_desc[::-1]

    q_flat = q_asc[inverse]

    q_matrix = q_flat.reshape(
        observed_scores.shape
    )


    threshold_rows = []

    for i, threshold in enumerate(thresholds_desc):

        threshold_rows.append(
            {
                "score_threshold": float(threshold),
                "n_observed_pairs_ge_threshold": int(
                    n_observed[i]
                ),
                "mean_null_pairs_ge_threshold": float(
                    mean_null_discoveries[i]
                ),
                "empirical_fdr_raw": float(
                    fdr_raw_desc[i]
                ),
                "empirical_q": float(
                    q_desc[i]
                ),
            }
        )


    return (
        q_matrix,
        threshold_rows,
        shifts,
    )


# ============================================================
# Optional: save all lag-wise statistics
# ============================================================

def write_all_lag_statistics(
    path,
    patterns,
    cfus,
    window_hits,
    pattern_lag_starts,
    p_window,
    p_tables,
    score_tables,
    best_lag,
    best_score,
    q_matrix,
):
    """
    Recompute observed lag-wise statistics and stream them to disk.

    This avoids holding ~6.5 million Python dictionaries in memory.
    """

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fields = [
        "motion_slice_0based",
        "pattern_id",
        "cfu_slice_0based",
        "cfu_id",
        "pattern_n_members",
        "n_motion_events",
        "cfu_n_member_events",
        "cfu_n_onsets",
        "lag",
        "window_frames",
        "n_valid_motion_events",
        "k_hit_motion_events",
        "p_window",
        "p_value_binomial",
        "lag_score",
        "pair_best_lag",
        "pair_best_score",
        "q_empirical_global",
        "significant_pair",
        "significant_best_lag",
    ]

    cfu_idx = np.arange(
        len(cfus)
    )

    with path.open(
        "w",
        newline="",
    ) as f:

        writer = csv.writer(f)

        writer.writerow(fields)

        for pi, (
            ms,
            pid,
            nm,
            peaks,
        ) in enumerate(patterns):

            for li, lag in enumerate(LAGS):

                starts = pattern_lag_starts[pi][li]

                n_trials = len(starts)

                if n_trials == 0:
                    continue

                k = np.sum(
                    window_hits[:, starts],
                    axis=1,
                ).astype(np.int16)

                pvals = p_tables[n_trials][
                    cfu_idx,
                    k,
                ]

                scores = score_tables[n_trials][
                    cfu_idx,
                    k,
                ]

                rows = []

                for ci, (
                    cs,
                    cid,
                    n_member_events,
                    onsets,
                ) in enumerate(cfus):

                    pair_sig = (
                        q_matrix[pi, ci]
                        <= FDR_ALPHA
                    )

                    is_best = (
                        int(lag)
                        ==
                        int(best_lag[pi, ci])
                    )

                    rows.append(
                        [
                            ms,
                            pid,
                            cs,
                            cid,
                            nm,
                            len(peaks),
                            n_member_events,
                            len(onsets),
                            int(lag),
                            WINDOW_W,
                            n_trials,
                            int(k[ci]),
                            float(p_window[ci]),
                            float(pvals[ci]),
                            float(scores[ci]),
                            int(best_lag[pi, ci]),
                            float(best_score[pi, ci]),
                            float(q_matrix[pi, ci]),
                            int(pair_sig),
                            int(
                                pair_sig
                                and is_best
                            ),
                        ]
                    )

                writer.writerows(rows)


# ============================================================
# Main
# ============================================================

def main():

    RESULTS.mkdir(
        parents=True,
        exist_ok=True,
    )


    # ========================================================
    # Load motion patterns and CFUs
    # ========================================================

    patterns = []
    cfus = []

    for z in range(1, 13):

        patterns += [
            (
                z,
                pid,
                nm,
                peaks,
            )
            for pid, nm, peaks
            in motion_event_peaks(z)
        ]

        cfus += [
            (
                z,
                cid,
                n_member_events,
                onsets,
            )
            for cid, n_member_events, onsets
            in cfu_event_onsets(z)
        ]


    n_patterns = len(patterns)
    n_cfus = len(cfus)
    n_pairs = n_patterns * n_cfus
    n_lag_tests = n_pairs * len(LAGS)


    print(
        f"patterns={n_patterns}",
        f"cfus={n_cfus}",
        f"pairs={n_pairs}",
        f"lag_evaluations={n_lag_tests}",
        flush=True,
    )


    # ========================================================
    # Build CFU onset matrix
    # ========================================================

    onset_matrix = build_onset_matrix(
        cfus
    )

    observed_window_hits = build_window_hit_matrix(
        onset_matrix
    )


    # ========================================================
    # CFU baseline onset rates
    # ========================================================

    cfu_n_onsets = np.asarray(
        [
            len(onsets)
            for _, _, _, onsets
            in cfus
        ],
        dtype=float,
    )

    burst_rate = (
        cfu_n_onsets
        /
        T
    )

    p_window = (
        1.0
        -
        (1.0 - burst_rate) ** WINDOW_W
    )

    p_window = np.clip(
        p_window,
        0.0,
        1.0,
    )


    # ========================================================
    # Precompute motion lag windows
    # ========================================================

    (
        pattern_lag_starts,
        unique_n_trials,
    ) = precompute_pattern_lag_starts(
        patterns
    )


    # ========================================================
    # Binomial lookup tables
    # ========================================================

    (
        p_tables,
        score_tables,
    ) = build_binomial_lookup(
        unique_n_trials,
        p_window,
    )


    # ========================================================
    # Observed best-lag statistics
    # ========================================================

    print(
        "Calculating observed best-lag pair statistics...",
        flush=True,
    )

    (
        best_score,
        best_p,
        best_lag,
        best_k,
        best_n_trials,
    ) = compute_best_pair_scores(
        observed_window_hits,
        pattern_lag_starts,
        p_tables,
        score_tables,
        return_details=True,
    )


    # ========================================================
    # Global empirical FDR
    # ========================================================

    (
        q_matrix,
        threshold_rows,
        null_shifts,
    ) = empirical_global_fdr(
        best_score,
        onset_matrix,
        pattern_lag_starts,
        p_tables,
        score_tables,
    )


    # ========================================================
    # Pair-level output
    # ========================================================

    pair_rows = []
    sig_rows = []

    for pi, (
        ms,
        pid,
        nm,
        peaks,
    ) in enumerate(patterns):

        for ci, (
            cs,
            cid,
            n_member_events,
            onsets,
        ) in enumerate(cfus):

            q = float(
                q_matrix[pi, ci]
            )

            row = {
                "motion_slice_0based": ms,
                "pattern_id": pid,
                "cfu_slice_0based": cs,
                "cfu_id": cid,
                "pattern_n_members": nm,
                "n_motion_events": len(peaks),
                "cfu_n_member_events": n_member_events,
                "cfu_n_onsets": len(onsets),
                "best_lag": int(
                    best_lag[pi, ci]
                ),
                "window_frames": WINDOW_W,
                "n_valid_motion_events_at_best_lag": int(
                    best_n_trials[pi, ci]
                ),
                "k_hit_motion_events_at_best_lag": int(
                    best_k[pi, ci]
                ),
                "p_window": float(
                    p_window[ci]
                ),
                "best_lag_binomial_p": float(
                    best_p[pi, ci]
                ),
                "pair_score": float(
                    best_score[pi, ci]
                ),
                "q_empirical_global": q,
                "significant": int(
                    q <= FDR_ALPHA
                ),
            }

            pair_rows.append(row)

            if q <= FDR_ALPHA:
                sig_rows.append(row)


    save_csv(
        RESULTS
        / "all_pair_best_lag_statistics.csv",
        pair_rows,
    )

    save_csv(
        RESULTS
        / "empirical_FDR_significant_pairs.csv",
        sig_rows,
    )

    save_csv(
        RESULTS
        / "empirical_fdr_thresholds.csv",
        threshold_rows,
    )


    # ========================================================
    # Save null shifts
    # ========================================================

    shift_rows = [
        {
            "shift_frames": int(s),
            "shift_seconds": float(
                s * FRAME_SECONDS
            ),
            "circular_distance_frames": int(
                min(s, T - s)
            ),
        }
        for s in null_shifts
    ]

    save_csv(
        RESULTS / "null_shifts.csv",
        shift_rows,
    )


    # ========================================================
    # Optional all-lag output
    # ========================================================

    if SAVE_ALL_LAG_ROWS:

        print(
            "Writing all lag-wise statistics...",
            flush=True,
        )

        write_all_lag_statistics(
            RESULTS
            / "all_pair_lag_statistics.csv",
            patterns,
            cfus,
            observed_window_hits,
            pattern_lag_starts,
            p_window,
            p_tables,
            score_tables,
            best_lag,
            best_score,
            q_matrix,
        )


    # ========================================================
    # Summary
    # ========================================================

    n_sig = int(
        np.sum(
            q_matrix <= FDR_ALPHA
        )
    )

    summary = [
        {
            "n_patterns": n_patterns,
            "n_cfus": n_cfus,
            "n_unique_pairs": n_pairs,
            "n_lag_values": len(LAGS),
            "n_total_lag_evaluations": n_lag_tests,
            "n_null_shifts": len(null_shifts),
            "null_guard_frames": NULL_GUARD_FRAMES,
            "window_frames": WINDOW_W,
            "lag_min": LAG_MIN,
            "lag_max": LAG_MAX,
            "fdr_alpha": FDR_ALPHA,
            "n_significant_pairs": n_sig,
        }
    ]

    save_csv(
        RESULTS / "summary_global.csv",
        summary,
    )


    # ========================================================
    # Save configuration
    # ========================================================

    config_text = f"""
Global all-slice motion-pattern x CFU onset co-occurrence

CFU timing:
    AQuA2 cfuInfo1{{i,4}} rising-time/onset timeline

Patterns retained:
    pattern members >= {MIN_PATTERN_MEMBERS}
    motion events >= {MIN_MOTION_EVENTS}

Motion event detection:
    RMS activity
    find_peaks prominence = {MOTION_PROMINENCE_FACTOR} * SD
    minimum peak distance = {MOTION_MIN_DISTANCE} frames

Co-occurrence:
    window = {WINDOW_W} frames
    lag = {LAG_MIN} ... {LAG_MAX}

Pair statistic:
    lag-wise binomial enrichment p-value
    score(lag) = -log10(p)
    pair_score = max_lag score(lag)

Lag multiple testing:
    No Bonferroni correction.
    The complete lag search is repeated inside every null realization.

Null:
    Same circular temporal shift applied to ALL CFUs.
    Near-zero shifts excluded:
        circular distance <= {NULL_GUARD_FRAMES} frames

Number of null shifts:
    {len(null_shifts)}

Global correction:
    empirical_FDR(score threshold)
        =
    expected_null_discoveries
        /
    observed_discoveries

Significance:
    empirical global q <= {FDR_ALPHA}
"""

    (
        OUT
        / "run_config.txt"
    ).write_text(
        config_text.strip() + "\n"
    )


    print(
        summary[0],
        flush=True,
    )


if __name__ == "__main__":
    main()
